In [ ]:
import pandas as pd
import numpy as np

## **상관계수 분석**
상관계수: 두 변수 x값과 y값을 z값으로 표준화해 Zx * Zy를 모두 더한다음, n(총 개수)으로 나눠준 것

*   0 ~ 0.2 : 매우 약한 상관관계
*   0.2 ~ 0.4 : 약한 상관관계
*   0.4 ~ 0.6 : 어느 정도의 상관관계
*   0.6 ~ 0.8 : 강한 상관관계
*   0.8 ~ 1.0 : 매우 강한 상관관계

상관계수의 범위는 -1부터 1까지 음수가 나오면 음의 상관관계, 양수가 나오면 양의 상관관계

# **제조업**

In [ ]:
#파일 불러오기
df = pd.read_csv('/content/drive/My Drive/최종-대분류-산업별-데이터-0.csv', index_col=0, encoding='UTF-8')
df.head()

산업분류     ID  지역  ... 인구 대비 산업체 수  인구 대비 산업체 종사자 수  종사자수 대비 산업체 수
0  제조업(10~34)  서울 종로  서울  ...    2.808814         8.274513      33.945375
1  제조업(10~34)  서울 중구  서울  ...    7.218195        22.652296      31.865179
2  제조업(10~34)  서울 용산  서울  ...    0.424786         1.401704      30.304936
3  제조업(10~34)  서울 성동  서울  ...    1.448520         8.820845      16.421551
4  제조업(10~34)  서울 광진  서울  ...    0.471151         1.986729      23.714921

[5 rows x 12 columns]

In [ ]:
df = df.drop(['지역', '행정구역'], axis=1)

In [ ]:
np.corrcoef(df['인구 대비 산업체 수'], df['인구 대비 확진자 수'])
#매우 약한 상관관계<-관계 거의 없음

array([[1.        , 0.05100557],
       [0.05100557, 1.        ]])

In [ ]:
np.corrcoef(df['인구 대비 산업체 종사자 수'], df['인구 대비 확진자 수'])
#매우 약한 음의 상관관계 <- 관계 거의 없음

array([[ 1.        , -0.03167564],
       [-0.03167564,  1.        ]])

In [ ]:
np.corrcoef(df['종사자수 대비 산업체 수'], df['인구 대비 확진자 수'])
#매우 약한 상관관계<-관계 거의 없음

array([[1.        , 0.17474401],
       [0.17474401, 1.        ]])

In [ ]:
df.sort_values(by='인구 대비 산업체 수', ascending=False).head()

산업분류     ID    인구 수  ...  인구 대비 산업체 수  인구 대비 산업체 종사자 수  종사자수 대비 산업체 수
1    제조업(10~34)  서울 중구  129797  ...     7.218195        22.652296      31.865179
36   제조업(10~34)  부산 강서  121351  ...     5.337410        57.104597       9.346725
200  제조업(10~34)     고령   32660  ...     4.537661        32.973056      13.761723
220  제조업(10~34)     함안   67520  ...     3.858116        35.284360      10.934352
101  제조업(10~34)     포천  161564  ...     3.701939        27.027679      13.696842

[5 rows x 10 columns]

In [ ]:
df = df.drop(['산업분류', '인구 수', '확진자 수', '총사업체수', '총종사자수'], axis=1)
df.head()

ID  인구 대비 확진자 수  인구 대비 산업체 수  인구 대비 산업체 종사자 수  종사자수 대비 산업체 수
0  서울 종로     0.017092     2.808814         8.274513      33.945375
1  서울 중구     0.013868     7.218195        22.652296      31.865179
2  서울 용산     0.023354     0.424786         1.401704      30.304936
3  서울 성동     0.018579     1.448520         8.820845      16.421551
4  서울 광진     0.006072     0.471151         1.986729      23.714921

# **운수 및 창고업**

In [ ]:
#파일 불러오기
df2 = pd.read_csv('/content/drive/My Drive/최종-대분류-산업별-데이터-1.csv', index_col=0, encoding='UTF-8')
df2.head()

산업분류     ID  지역  ... 인구 대비 산업체 수  인구 대비 산업체 종사자 수  종사자수 대비 산업체 수
0  운수 및 창고업(49~52)  서울 종로  서울  ...    0.878665         4.595897      19.118457
1  운수 및 창고업(49~52)  서울 중구  서울  ...    1.191861        11.029531      10.806091
2  운수 및 창고업(49~52)  서울 용산  서울  ...    0.551252         1.726463      31.929556
3  운수 및 창고업(49~52)  서울 성동  서울  ...    0.856921         2.820441      30.382526
4  운수 및 창고업(49~52)  서울 광진  서울  ...    0.695272         1.608594      43.222375

[5 rows x 12 columns]

In [ ]:
np.corrcoef(df2['인구 대비 산업체 수'], df2['인구 대비 확진자 수'])
#매우 약한 상관관계 <-관계 거의 없음

array([[1.        , 0.01992208],
       [0.01992208, 1.        ]])

In [ ]:
np.corrcoef(df2['인구 대비 산업체 종사자 수'], df2['인구 대비 확진자 수'])
#매우 약한 음의 상관관계 <- 관계 거의 없음

array([[ 1.        , -0.03378918],
       [-0.03378918,  1.        ]])

In [ ]:
np.corrcoef(df2['종사자수 대비 산업체 수'], df2['인구 대비 확진자 수'])
#매우 약한 상관관계<-관계 거의 없음

array([[1.        , 0.09814335],
       [0.09814335, 1.        ]])

# **소분류 산업별 데이터**

In [ ]:
#0_방문판매업
#파일 불러오기
df3 = pd.read_csv('/content/drive/My Drive/Cayley/최종-소분류-산업별-데이터-0.csv', index_col=0, encoding='UTF-8')
df3.head()

산업분류     ID  지역  ... 인구 대비 산업체 수  인구 대비 산업체 종사자 수  종사자수 대비 산업체 수
0  방문 판매업  서울 종로  서울  ...    0.008863         0.027854      31.818182
1  방문 판매업  서울 중구  서울  ...    0.013868         0.451474       3.071672
2  방문 판매업  서울 용산  서울  ...    0.010576         0.041862      25.263158
3  방문 판매업  서울 성동  서울  ...    0.005215         0.046611      11.188811
4  방문 판매업  서울 광진  서울  ...    0.007452         0.095776       7.780980

[5 rows x 12 columns]

In [ ]:
np.corrcoef(df3['인구 대비 산업체 수'], df3['인구 대비 확진자 수'])
#매우 약한 상관관계 <-관계 거의 없음

array([[1.        , 0.06759154],
       [0.06759154, 1.        ]])

In [ ]:
np.corrcoef(df3['인구 대비 산업체 종사자 수'], df3['인구 대비 확진자 수'])
#매우 약한 상관관계 <- 관계 거의 없음

array([[1.        , 0.17990617],
       [0.17990617, 1.        ]])

In [ ]:
np.corrcoef(df3['종사자수 대비 산업체 수'], df3['인구 대비 확진자 수'])
#매우 약한 상관관계<-관계 거의 없음

array([[1.        , 0.03942181],
       [0.03942181, 1.        ]])

In [ ]:
#1_택배업
#파일 불러오기
df4 = pd.read_csv('/content/drive/My Drive/Cayley/최종-소분류-산업별-데이터-1.csv', index_col=0, encoding='UTF-8')
df4.head()

산업분류     ID  지역  ... 인구 대비 산업체 수  인구 대비 산업체 종사자 수  종사자수 대비 산업체 수
0  택배업  서울 종로  서울  ...    0.017092         0.163325      10.465116
1  택배업  서울 중구  서울  ...    0.054701         1.553195       3.521825
2  택배업  서울 용산  서울  ...    0.012779         0.075792      16.860465
3  택배업  서울 성동  서울  ...    0.011408         0.116690       9.776536
4  택배업  서울 광진  서울  ...    0.002760         0.103228       2.673797

[5 rows x 12 columns]

In [ ]:
np.corrcoef(df4['인구 대비 산업체 수'], df4['인구 대비 확진자 수'])
#매우 약한 상관관계 <-관계 거의 없음

array([[ 1.        , -0.03122703],
       [-0.03122703,  1.        ]])

In [ ]:
np.corrcoef(df4['인구 대비 산업체 종사자 수'], df4['인구 대비 확진자 수'])
#매우 약한 음의 상관관계 <- 관계 거의 없음

array([[ 1.        , -0.00175949],
       [-0.00175949,  1.        ]])

In [ ]:
np.corrcoef(df4['종사자수 대비 산업체 수'], df4['인구 대비 확진자 수'])
#매우 약한 음의 상관관계<-관계 거의 없음

array([[ 1.        , -0.04759785],
       [-0.04759785,  1.        ]])

In [ ]:
#2_항공 여객 운송업
#파일 불러오기
df5 = pd.read_csv('/content/drive/My Drive/Cayley/최종-소분류-산업별-데이터-2.csv', index_col=0, encoding='UTF-8')
df5.head()

산업분류     ID  지역  ... 인구 대비 산업체 수  인구 대비 산업체 종사자 수  종사자수 대비 산업체 수
0  항공 여객 운송업  서울 종로  서울  ...    0.001899         0.106984       1.775148
1  항공 여객 운송업  서울 중구  서울  ...    0.019261         0.551631       3.491620
2  항공 여객 운송업  서울 용산  서울  ...    0.000441         0.000000       0.000000
3  항공 여객 운송업  서울 성동  서울  ...    0.000000         0.000000       0.000000
4  항공 여객 운송업  서울 광진  서울  ...    0.000000         0.000000       0.000000

[5 rows x 12 columns]

In [ ]:
np.corrcoef(df5['인구 대비 산업체 수'], df5['인구 대비 확진자 수'])
#???????????

array([[ 1.00000000e+00, -9.80819089e-04],
       [-9.80819089e-04,  1.00000000e+00]])

In [ ]:
np.corrcoef(df5['인구 대비 산업체 종사자 수'], df5['인구 대비 확진자 수'])
#매우 약한 음의 상관관계 <- 관계 거의 없음

array([[ 1.        , -0.01176867],
       [-0.01176867,  1.        ]])

In [ ]:
np.corrcoef(df5['종사자수 대비 산업체 수'], df5['인구 대비 확진자 수'])
#매우 약한 음의 상관관계<-관계 거의 없음

array([[ 1.        , -0.01703827],
       [-0.01703827,  1.        ]])

In [ ]:
#3_주점업
#파일 불러오기
df6 = pd.read_csv('/content/drive/My Drive/Cayley/최종-소분류-산업별-데이터-3.csv', index_col=0, encoding='UTF-8')
df6.head()

산업분류     ID  지역  ... 인구 대비 산업체 수  인구 대비 산업체 종사자 수  종사자수 대비 산업체 수
0  주점업  서울 종로  서울  ...    0.562143         1.564884      35.922330
1  주점업  서울 중구  서울  ...    0.481521         1.289706      37.335723
2  주점업  서울 용산  서울  ...    0.314183         0.926244      33.920076
3  주점업  서울 성동  서울  ...    0.146025         0.336054      43.452958
4  주점업  서울 광진  서울  ...    0.237370         0.587352      40.413534

[5 rows x 12 columns]

In [ ]:
np.corrcoef(df6['인구 대비 산업체 수'], df6['인구 대비 확진자 수'])
#매우 약한 상관관계 <- 상관관계 거의 없음

array([[1.        , 0.01860987],
       [0.01860987, 1.        ]])

In [ ]:
np.corrcoef(df6['인구 대비 산업체 종사자 수'], df6['인구 대비 확진자 수'])
#매우 약한 상관관계 <- 관계 거의 없음

array([[1.        , 0.06180729],
       [0.06180729, 1.        ]])

In [ ]:
np.corrcoef(df6['종사자수 대비 산업체 수'], df6['인구 대비 확진자 수'])
#매우 약한 음의 상관관계<-관계 거의 없음

array([[ 1.        , -0.07003899],
       [-0.07003899,  1.        ]])

In [ ]:
#4_콜센터 및 텔러마케팅 서비스업
#파일 불러오기
df7 = pd.read_csv('/content/drive/My Drive/Cayley/최종-소분류-산업별-데이터-4.csv', index_col=0, encoding='UTF-8')
df7.head()

산업분류     ID  지역  ... 인구 대비 산업체 수  인구 대비 산업체 종사자 수  종사자수 대비 산업체 수
0  콜센터 및 텔레마케팅 서비스업  서울 종로  서울  ...    0.004431         0.472251       0.938338
1  콜센터 및 텔레마케팅 서비스업  서울 중구  서울  ...    0.018490         1.439941       1.284109
2  콜센터 및 텔레마케팅 서비스업  서울 용산  서울  ...    0.004847         0.419938       1.154250
3  콜센터 및 텔레마케팅 서비스업  서울 성동  서울  ...    0.004563         0.595184       0.766703
4  콜센터 및 텔레마케팅 서비스업  서울 광진  서울  ...    0.002484         0.032293       7.692308

[5 rows x 12 columns]

In [ ]:
np.corrcoef(df7['인구 대비 산업체 수'], df7['인구 대비 확진자 수'])
#매우 약한 상관관계 <- 상관관계 거의 없음

array([[1.        , 0.16969572],
       [0.16969572, 1.        ]])

In [ ]:
np.corrcoef(df7['인구 대비 산업체 종사자 수'], df7['인구 대비 확진자 수'])
#매우 약한 상관관계 <- 관계 거의 없음

array([[1.       , 0.0532794],
       [0.0532794, 1.       ]])

In [ ]:
np.corrcoef(df7['종사자수 대비 산업체 수'], df7['인구 대비 확진자 수'])
#매우 약한 음의 상관관계<-관계 거의 없음

array([[1.        , 0.01955839],
       [0.01955839, 1.        ]])

In [ ]:
#5_사회복지 서비스업
#파일 불러오기
df8 = pd.read_csv('/content/drive/My Drive/Cayley/최종-소분류-산업별-데이터-5.csv', index_col=0, encoding='UTF-8')
df8.head()

산업분류     ID  지역  ... 인구 대비 산업체 수  인구 대비 산업체 종사자 수  종사자수 대비 산업체 수
0  사회복지 서비스업  서울 종로  서울  ...    0.138637         1.635152       8.478513
1  사회복지 서비스업  서울 중구  서울  ...    0.143301         2.221931       6.449376
2  사회복지 서비스업  서울 용산  서울  ...    0.112806         1.436516       7.852761
3  사회복지 서비스업  서울 성동  서울  ...    0.099415         1.229481       8.085896
4  사회복지 서비스업  서울 광진  서울  ...    0.093016         1.400205       6.643012

[5 rows x 12 columns]

In [ ]:
np.corrcoef(df8['인구 대비 산업체 수'], df8['인구 대비 확진자 수'])
#매우 약한 음의 상관관계 <- 상관관계 거의 없음

array([[ 1.        , -0.07006533],
       [-0.07006533,  1.        ]])

In [ ]:
np.corrcoef(df8['인구 대비 산업체 종사자 수'], df8['인구 대비 확진자 수'])
#매우 약한 상관관계 <- 관계 거의 없음

array([[1.        , 0.00676741],
       [0.00676741, 1.        ]])

In [ ]:
np.corrcoef(df8['종사자수 대비 산업체 수'], df8['인구 대비 확진자 수'])
#매우 약한 음의 상관관계<-관계 거의 없음

array([[ 1.        , -0.10390528],
       [-0.10390528,  1.        ]])

In [ ]:
#6_개인 간병 및 유사 서비스업
#파일 불러오기
df9 = pd.read_csv('/content/drive/My Drive/Cayley/최종-소분류-산업별-데이터-6.csv', index_col=0, encoding='UTF-8')
df9.head()

산업분류     ID  지역  ... 인구 대비 산업체 수  인구 대비 산업체 종사자 수  종사자수 대비 산업체 수
0  개인 간병 및 유사 서비스업  서울 종로  서울  ...    0.001266         0.000000       0.000000
1  개인 간병 및 유사 서비스업  서울 중구  서울  ...    0.002311         0.031588       7.317073
2  개인 간병 및 유사 서비스업  서울 용산  서울  ...    0.000441         0.000000       0.000000
3  개인 간병 및 유사 서비스업  서울 성동  서울  ...    0.001956         0.018579      10.526316
4  개인 간병 및 유사 서비스업  서울 광진  서울  ...    0.001656         0.031741       5.217391

[5 rows x 12 columns]

In [ ]:
np.corrcoef(df9['인구 대비 산업체 수'], df9['인구 대비 확진자 수'])
#매우 약한 음의 상관관계 <- 상관관계 거의 없음

array([[ 1.        , -0.06483003],
       [-0.06483003,  1.        ]])

In [ ]:
np.corrcoef(df9['인구 대비 산업체 종사자 수'], df9['인구 대비 확진자 수'])
#매우 약한 음의 상관관계 <- 관계 거의 없음

array([[ 1.        , -0.06049525],
       [-0.06049525,  1.        ]])

In [ ]:
np.corrcoef(df9['종사자수 대비 산업체 수'], df9['인구 대비 확진자 수'])
#매우 약한 음의 상관관계<-관계 거의 없음

array([[ 1.        , -0.06005356],
       [-0.06005356,  1.        ]])

In [ ]:
#7_종교 단체
#파일 불러오기
df10 = pd.read_csv('/content/drive/My Drive/Cayley/최종-소분류-산업별-데이터-7.csv', index_col=0, encoding='UTF-8')
df10.head()

산업분류     ID  지역  ... 인구 대비 산업체 수  인구 대비 산업체 종사자 수  종사자수 대비 산업체 수
0  종교 단체  서울 종로  서울  ...    0.257649         1.288244      20.000000
1  종교 단체  서울 중구  서울  ...    0.125581         0.736535      17.050209
2  종교 단체  서울 용산  서울  ...    0.079317         0.568878      13.942680
3  종교 단체  서울 성동  서울  ...    0.065516         0.211867      30.923077
4  종교 단체  서울 광진  서울  ...    0.091912         0.248134      37.041157

[5 rows x 12 columns]

In [ ]:
np.corrcoef(df10['인구 대비 산업체 수'], df10['인구 대비 확진자 수'])
#매우 약한 음의 상관관계 <- 상관관계 거의 없음

array([[ 1.        , -0.08128433],
       [-0.08128433,  1.        ]])

In [ ]:
np.corrcoef(df10['인구 대비 산업체 종사자 수'], df10['인구 대비 확진자 수'])
#매우 약한 상관관계 <- 관계 거의 없음

array([[1.        , 0.01784979],
       [0.01784979, 1.        ]])

In [ ]:
np.corrcoef(df10['종사자수 대비 산업체 수'], df10['인구 대비 확진자 수'])
#매우 약한 음의 상관관계<-관계 거의 없음

array([[ 1.       , -0.1616867],
       [-0.1616867,  1.       ]])

In [ ]:
#8_택시 운송업
#파일 불러오기
df11 = pd.read_csv('/content/drive/My Drive/Cayley/최종-소분류-산업별-데이터-8.csv', index_col=0, encoding='UTF-8')
df11.head()

산업분류     ID  지역  ... 인구 대비 산업체 수  인구 대비 산업체 종사자 수  종사자수 대비 산업체 수
0  택시 운송업  서울 종로  서울  ...    0.140536         0.140536     100.000000
1  택시 운송업  서울 중구  서울  ...    0.181052         0.184134      98.326360
2  택시 운송업  서울 용산  서울  ...    0.199173         0.255136      78.065630
3  택시 운송업  서울 성동  서울  ...    0.369627         0.817481      45.215311
4  택시 운송업  서울 광진  서울  ...    0.313825         0.528562      59.373368

[5 rows x 12 columns]

In [ ]:
np.corrcoef(df11['인구 대비 산업체 수'], df11['인구 대비 확진자 수'])
#매우 약한 상관관계 <- 상관관계 거의 없음

array([[1.        , 0.07194195],
       [0.07194195, 1.        ]])

In [ ]:
np.corrcoef(df11['인구 대비 산업체 종사자 수'], df11['인구 대비 확진자 수'])
#매우 약한 상관관계 <- 관계 거의 없음

array([[1.        , 0.05082231],
       [0.05082231, 1.        ]])

In [ ]:
np.corrcoef(df11['종사자수 대비 산업체 수'], df11['인구 대비 확진자 수'])
#매우 약한 상관관계<-관계 거의 없음

array([[1.        , 0.01090909],
       [0.01090909, 1.        ]])

In [108]:
fp1 = np.polyfit(df3['인구 대비 산업체 종사자 수'], df3['인구 대비 확진자 수'], 1)
fp1

array([0.05694698, 0.01330211])