# 협회 및 단체, 수리 및 기타 개인 서비스업(94~96) 상관계수 분석

* 작성자: 김가윤

In [1]:
import numpy as np
import pandas as pd

In [2]:
ser = pd.read_csv('C:\\Users\\Owner\\Documents\\GitHub\\cosadama\\PROJECTS\\cayley\\최종-대분류-산업별-데이터-7.csv')
ser.head()

Unnamed: 0                             산업분류     ID  지역 행정구역    인구 수  확진자 수  \
0           0  협회 및 단체, 수리 및 기타 개인 서비스업(94~96)  서울 종로  서울  종로구  157967     27   
1           1  협회 및 단체, 수리 및 기타 개인 서비스업(94~96)  서울 중구  서울   중구  129797     18   
2           2  협회 및 단체, 수리 및 기타 개인 서비스업(94~96)  서울 용산  서울  용산구  226938     53   
3           3  협회 및 단체, 수리 및 기타 개인 서비스업(94~96)  서울 성동  서울  성동구  306796     57   
4           4  협회 및 단체, 수리 및 기타 개인 서비스업(94~96)  서울 광진  서울  광진구  362304     22   

   총사업체수  총종사자수  인구 대비 확진자 수  인구 대비 산업체 수  인구 대비 산업체 종사자 수  종사자수 대비 산업체 수  
0   2448   7672     0.017092     1.549691         4.856711      31.908238  
1   2138   8366     0.013868     1.647188         6.445449      25.555821  
2   1641   5939     0.023354     0.723105         2.617014      27.630914  
3   2115   7612     0.018579     0.689383         2.481128      27.785076  
4   2587   5608     0.006072     0.714041         1.547871      46.130528

In [3]:
ser.drop(["Unnamed: 0"], axis=1, inplace=True)

In [4]:
ser

산업분류     ID       지역  행정구역    인구 수  확진자 수  \
0    협회 및 단체, 수리 및 기타 개인 서비스업(94~96)  서울 종로       서울   종로구  157967     27   
1    협회 및 단체, 수리 및 기타 개인 서비스업(94~96)  서울 중구       서울    중구  129797     18   
2    협회 및 단체, 수리 및 기타 개인 서비스업(94~96)  서울 용산       서울   용산구  226938     53   
3    협회 및 단체, 수리 및 기타 개인 서비스업(94~96)  서울 성동       서울   성동구  306796     57   
4    협회 및 단체, 수리 및 기타 개인 서비스업(94~96)  서울 광진       서울   광진구  362304     22   
..                               ...    ...      ...   ...     ...    ...   
226  협회 및 단체, 수리 및 기타 개인 서비스업(94~96)     함양     경상남도   함양군   38005      1   
227  협회 및 단체, 수리 및 기타 개인 서비스업(94~96)     거창     경상남도   거창군   60020     19   
228  협회 및 단체, 수리 및 기타 개인 서비스업(94~96)     합천     경상남도   합천군   42856     10   
229  협회 및 단체, 수리 및 기타 개인 서비스업(94~96)     제주  제주특별자치도   제주시  482932     26   
230  협회 및 단체, 수리 및 기타 개인 서비스업(94~96)    서귀포  제주특별자치도  서귀포시  175350     26   

     총사업체수  총종사자수  인구 대비 확진자 수  인구 대비 산업체 수  인구 대비 산업체 종사자 수  종사자수 대비 산업체 수  
0     2448   7672     0.017092     1.549691         4.856711      31.908238  
1     2138   8366     0.013868     1.647188         6.445449      25.555821  
2     1641   5939     0.023354     0.723105         2.617014      27.630914  
3     2115   7612     0.018579     0.689383         2.481128      27.785076  
4     2587   5608     0.006072     0.714041         1.547871      46.130528  
..     ...    ...          ...          ...              ...            ...  
226    370    673     0.002631     0.973556         1.770820      54.977712  
227    590    926     0.031656     0.983006         1.542819      63.714903  
228    418    820     0.023334     0.975359         1.913384      50.975610  
229   4184   9507     0.005384     0.866375         1.968600      44.009677  
230   1403   2919     0.014827     0.800114         1.664671      48.064406  

[231 rows x 12 columns]

In [6]:
np.corrcoef(ser['인구 대비 산업체 수'], ser['인구 대비 확진자 수'])

array([[1.        , 0.13852745],
       [0.13852745, 1.        ]])

In [7]:
np.corrcoef(ser['인구 대비 산업체 종사자 수'], ser['인구 대비 확진자 수'])

array([[1.        , 0.11702644],
       [0.11702644, 1.        ]])

In [8]:
np.corrcoef(ser['종사자수 대비 산업체 수'], ser['인구 대비 확진자 수'])

array([[ 1.        , -0.01027273],
       [-0.01027273,  1.        ]])