# 예술, 스포츠 및 여가관련 서비스업(90~91) 상관계수 분석

* 작성자: 김가윤

In [1]:
import pandas as pd
import numpy as np

In [2]:
tmp = pd.read_csv('C:\\Users\\Owner\\Documents\\GitHub\\cosadama\\PROJECTS\\cayley\\최종-대분류-산업별-데이터-6.csv')
tmp.head()

Unnamed: 0                        산업분류     ID  지역 행정구역    인구 수  확진자 수  \
0           0  예술, 스포츠 및 여가관련 서비스업(90~91)  서울 종로  서울  종로구  157967     27   
1           1  예술, 스포츠 및 여가관련 서비스업(90~91)  서울 중구  서울   중구  129797     18   
2           2  예술, 스포츠 및 여가관련 서비스업(90~91)  서울 용산  서울  용산구  226938     53   
3           3  예술, 스포츠 및 여가관련 서비스업(90~91)  서울 성동  서울  성동구  306796     57   
4           4  예술, 스포츠 및 여가관련 서비스업(90~91)  서울 광진  서울  광진구  362304     22   

   총사업체수  총종사자수  인구 대비 확진자 수  인구 대비 산업체 수  인구 대비 산업체 종사자 수  종사자수 대비 산업체 수  
0    909   6227     0.017092     0.575437         3.941963      14.597720  
1    558   3723     0.013868     0.429902         2.868325      14.987913  
2    408   2831     0.023354     0.179785         1.247477      14.411869  
3    581   2157     0.018579     0.189377         0.703073      26.935559  
4   1033   3862     0.006072     0.285120         1.065956      26.747799

In [9]:
#tmp.drop(["Unnamed: 0"], axis=1, inplace=True)

In [8]:
tmp

산업분류     ID       지역  행정구역    인구 수  확진자 수  총사업체수  \
0    예술, 스포츠 및 여가관련 서비스업(90~91)  서울 종로       서울   종로구  157967     27    909   
1    예술, 스포츠 및 여가관련 서비스업(90~91)  서울 중구       서울    중구  129797     18    558   
2    예술, 스포츠 및 여가관련 서비스업(90~91)  서울 용산       서울   용산구  226938     53    408   
3    예술, 스포츠 및 여가관련 서비스업(90~91)  서울 성동       서울   성동구  306796     57    581   
4    예술, 스포츠 및 여가관련 서비스업(90~91)  서울 광진       서울   광진구  362304     22   1033   
..                          ...    ...      ...   ...     ...    ...    ...   
226  예술, 스포츠 및 여가관련 서비스업(90~91)     함양     경상남도   함양군   38005      1     61   
227  예술, 스포츠 및 여가관련 서비스업(90~91)     거창     경상남도   거창군   60020     19    119   
228  예술, 스포츠 및 여가관련 서비스업(90~91)     합천     경상남도   합천군   42856     10     69   
229  예술, 스포츠 및 여가관련 서비스업(90~91)     제주  제주특별자치도   제주시  482932     26   1341   
230  예술, 스포츠 및 여가관련 서비스업(90~91)    서귀포  제주특별자치도  서귀포시  175350     26    460   

     총종사자수  인구 대비 확진자 수  인구 대비 산업체 수  인구 대비 산업체 종사자 수  종사자수 대비 산업체 수  
0     6227     0.017092     0.575437         3.941963      14.597720  
1     3723     0.013868     0.429902         2.868325      14.987913  
2     2831     0.023354     0.179785         1.247477      14.411869  
3     2157     0.018579     0.189377         0.703073      26.935559  
4     3862     0.006072     0.285120         1.065956      26.747799  
..     ...          ...          ...              ...            ...  
226    306     0.002631     0.160505         0.805157      19.934641  
227    392     0.031656     0.198267         0.653116      30.357143  
228    353     0.023334     0.161004         0.823689      19.546742  
229   7111     0.005384     0.277679         1.472464      18.858107  
230   4467     0.014827     0.262332         2.547476      10.297739  

[231 rows x 12 columns]

In [10]:
np.corrcoef(tmp['인구 대비 산업체 수'], tmp['인구 대비 확진자 수'])

array([[1.        , 0.05044235],
       [0.05044235, 1.        ]])

In [11]:
np.corrcoef(tmp['인구 대비 산업체 종사자 수'], tmp['인구 대비 확진자 수'])

array([[ 1.        , -0.02553976],
       [-0.02553976,  1.        ]])

In [13]:
np.corrcoef(tmp['종사자수 대비 산업체 수'], tmp['인구 대비 확진자 수'])

array([[1.        , 0.08467817],
       [0.08467817, 1.        ]])